---
- name: Coping /etc/default/rabbitmq-server
  template:
    src: "rabbitmq-server.j2"
    dest: "/etc/default/rabbitmq-server"
    owner: root
    group: root
    mode: 0644

- name: Coping /etc/rabbitmq/rabbitmq.config
  template:
    src: "rabbitmq.config.j2"
    dest: "/etc/rabbitmq/rabbitmq.config"
    owner: rabbitmq
    group: rabbitmq
    mode: 0644

- name: Creating environment-specific configuration
  template:
    src: "rabbitmq-env.conf.j2"
    dest: "/etc/rabbitmq/rabbitmq-env.conf"
    owner: rabbitmq
    group: rabbitmq
    mode: 0644
    backup: yes
  when: rabbitmq_env_conf is defined

#- name: Creating vhost of rabbitmq
#  rabbitmq_vhost:
#    name: "{{ item }}"
#    state: present
#  with_items: "{{ rabbitmq_vhosts }}"

- name: Creating users of rabbitmq
  rabbitmq_user:
    user: "{{ item.user }}"
    password: "{{ item.password }}"
    configure_priv: "{{ item.configure_priv }}"
    read_priv: "{{ item.read_priv }}"
    write_priv: "{{ item.write_priv }}"
    vhost: "{{ item.vhost }}"
    tags: "{{ item.tags }}"
    state: present
  with_items: "{{ rabbitmq_users }}"
  run_once: yes 
  ignore_errors: yes

- name: Removing users
  rabbitmq_user:
    user: "{{ item }}"
    state: absent
  with_items: "{{ rabbitmq_remove_users }}"
  run_once: yes 

- name: Restarting rabbitmq-server
  service:
    name: rabbitmq-server
    state: restarted

