---
- name: Adding apt key
  apt_key:
    url: "{{ rabbitmq_apt_key }}"
    state: present

- name: Adding apt repository
  apt_repository:
    repo: "{{ rabbitmq_apt_repo }}"
    state: present
    update_cache: yes

- name: Installing rabbitmq-server
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - rabbitmq-server

- name: Enabling the RabbitMQ Management Console
  rabbitmq_plugin:
    names: "{{ item }}"
    state: enabled
  with_items: "{{ rabbitmq_plugins }}"

- name: Ensuring that the RabbitMQ service is running
  service:
    name: rabbitmq-server
    state: started
    enabled: yes

