---
- name: Installing epel-release and wget packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
#    - epel-release
#    - http://download.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-6.noarch.rpm
    - wget

- name: Downloading the erlang package of rpm
  get_url:
    url: "{{ rabbitmq_erlang_url }}"
    dest: "{{ rabbitmq_erlang_path }}"

- name: Installing the erlang package of rpm
  yum:
    name: "{{ rabbitmq_erlang_path }}"
    state: present

- name: Downloading the rabbitmq-server package of rpm
  get_url:
    url: "{{ rabbitmq_rpm_url }}"
    dest: "{{ rabbitmq_rpm_path }}"

- name: Importing rpm gpg key
  rpm_key:
    key: "{{ rabbitmq_rpm_key }}" 
    state: present 

- name: Installing the rabbitmq-server package of rpm
  yum:
    name: "{{ rabbitmq_rpm_path }}"
    state: present

- name: Setting firewall rule
  firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
  with_items: "{{ rabbitmq_firewalls }}"

- name: Reloading the firewall
  shell: "firewall-cmd --reload"

# This module requires libsemanage-python support
#- name: Setting nis_enalbed flag of SELinux
#  seboolean:
#    name: nis_enabled
#    state: yes 
#    persistent: yes

- name:
  shell: "setsebool -P nis_enabled 1"

- name: Enabling the RabbitMQ Management Console
  rabbitmq_plugin:
    names: "{{ item }}"
    state: enabled
  with_items: "{{ rabbitmq_plugins }}"

#- name: Ensuring that the RabbitMQ service is running
#  systemd:
#    name: rabbitmq-server
#    state: started
#    enabled: yes

- name: Ensuring that the RabbitMQ service is running
  service:
    name: rabbitmq-server
    state: started
    enabled: yes

