---
- include: hostname.yml

- include: install_debian.yml
  when: ansible_os_family == "Debian"

- include: install_redhat.yml
  when: ansible_os_family == "RedHat"

#- include: ssl.yml

- include: cluster.yml
  when: rabbitmq_enable_cluster

- include: config.yml

- include: rabbitmqadmin.yml
